testing changings,  fixed target, and fixed platform on some entrys

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,159 +36,159 @@ env:
   REDOT_MONO_BUILD_REPO: godotengine/godot-mono-builds
   
 jobs:
-  linux:
-    runs-on: "ubuntu-latest"
-    name: Linux ${{ matrix.name }}
-    if: github.event.inputs.platform == 'linux' || 'all'
-    env:
-      SCONSFLAGS: mono_static=yes
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: Editor & Templates
-            cache-name: linux
-            bin: ./redot-engine/bin/redot.linuxbsd.editor.x86_64
-            build-mono: false
+  # linux:
+  #   runs-on: "ubuntu-latest"
+  #   name: Linux ${{ matrix.name }}
+  #   if: github.event.inputs.platform == 'linux' || 'all'
+  #   env:
+  #     SCONSFLAGS: mono_static=yes
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - name: Editor & Templates
+  #           cache-name: linux
+  #           bin: ./redot-engine/bin/redot.linuxbsd.editor.x86_64
+  #           build-mono: false
 
-          - name: Editor & Templates w/ Mono
-            cache-name: linux-mono
-            bin: ./redot-engine/bin/redot.linuxbsd.editor.x86_64.mono
-            build-mono: true
+  #         - name: Editor & Templates w/ Mono
+  #           cache-name: linux-mono
+  #           bin: ./redot-engine/bin/redot.linuxbsd.editor.x86_64.mono
+  #           build-mono: true
 
-    steps:
-      - name: Checkout Build
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout Build
+  #       uses: actions/checkout@v4
 
-      - name: Checkout Redot source
-        uses: actions/checkout@v4
-        with:
-          repository: 'Redot-Engine/redot-engine'
-          ref: '${{ github.event.inputs.version }}'
-          path: redot-engine
+  #     - name: Checkout Redot source
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: 'Redot-Engine/redot-engine'
+  #         ref: '${{ github.event.inputs.version }}'
+  #         path: redot-engine
 
-      - name: Linux dependencies
-        shell: bash
-        run: |
-          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
-          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB8B81E14DA65431D7504EA8F63F0F2B90935439
-          sudo add-apt-repository -y "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
-          sudo apt update && sudo apt-get install -y xvfb libc6-dev p7zip-full p7zip-rar libwayland-dev \
-            mesa-vulkan-drivers dotnet-sdk-8.0
+  #     - name: Linux dependencies
+  #       shell: bash
+  #       run: |
+  #         sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
+  #         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB8B81E14DA65431D7504EA8F63F0F2B90935439
+  #         sudo add-apt-repository -y "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
+  #         sudo apt update && sudo apt-get install -y xvfb libc6-dev p7zip-full p7zip-rar libwayland-dev \
+  #           mesa-vulkan-drivers dotnet-sdk-8.0
 
-      # Linux Toolchain Setup
-      - name: Setup Linux toolchain
-        uses: ./.github/actions/redot-buildroot
-        with:
-          toolchain-name: "x86_64-godot-linux-gnu_sdk-buildroot"
+  #     # Linux Toolchain Setup
+  #     - name: Setup Linux toolchain
+  #       uses: ./.github/actions/redot-buildroot
+  #       with:
+  #         toolchain-name: "x86_64-godot-linux-gnu_sdk-buildroot"
 
-      # Cache
-      - name: Setup Godot build cache
-        uses: ./.github/actions/redot-cache
-        with:
-          cache-name: ${{ matrix.cache-name }}
-        continue-on-error: true
+  #     # Cache
+  #     - name: Setup Godot build cache
+  #       uses: ./.github/actions/redot-cache
+  #       with:
+  #         cache-name: ${{ matrix.cache-name }}
+  #       continue-on-error: true
 
-      - name: Setup python and scons
-        uses: ./.github/actions/redot-deps
+  #     - name: Setup python and scons
+  #       uses: ./.github/actions/redot-deps
 
-      # Mono Setup
-      - name: Setup mono
-        if: ${{ matrix.build-mono }}
-        uses: ./.github/actions/redot-mono
-        with:
-          mono-release: "linux-x86_64"
-          mono-bcl: "bcl-desktop"
+  #     # Mono Setup
+  #     - name: Setup mono
+  #       if: ${{ matrix.build-mono }}
+  #       uses: ./.github/actions/redot-mono
+  #       with:
+  #         mono-release: "linux-x86_64"
+  #         mono-bcl: "bcl-desktop"
 
-      - name: Mono precompilation
-        if: ${{ matrix.build-mono }}
-        uses: ./.github/actions/redot-build
-        with:
-          buildroot: "${{ github.workspace }}/x86_64-godot-linux-gnu_sdk-buildroot/bin"
-          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} module_mono_enabled=yes mono_glue=no copy_mono_root=yes mono_bcl=$HOME/mono-bcls/desktop-bcl/net_4_x mono_prefix=$HOME/mono-installs/desktop-linux-x86_64-release
-          platform: linuxbsd
-          target: editor
-          tools: true
+  #     - name: Mono precompilation
+  #       if: ${{ matrix.build-mono }}
+  #       uses: ./.github/actions/redot-build
+  #       with:
+  #         buildroot: "${{ github.workspace }}/x86_64-godot-linux-gnu_sdk-buildroot/bin"
+  #         sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} module_mono_enabled=yes mono_glue=no copy_mono_root=yes mono_bcl=$HOME/mono-bcls/desktop-bcl/net_4_x mono_prefix=$HOME/mono-installs/desktop-linux-x86_64-release
+  #         platform: linuxbsd
+  #         target: editor
+  #         tools: true
 
-      # Generate mono glue
-      - name: Generate Mono glue code
-        if: ${{ matrix.build-mono }}
-        run: |
-          DRI_PRIME=0 xvfb-run "./bin/redot.x11.tools.64.mono" --generate-mono-glue modules/mono/glue || true
+  #     # Generate mono glue
+  #     - name: Generate Mono glue code
+  #       if: ${{ matrix.build-mono }}
+  #       run: |
+  #         DRI_PRIME=0 xvfb-run "./bin/redot.x11.tools.64.mono" --generate-mono-glue modules/mono/glue || true
 
-      - name: Set Mono scons flags
-        if: ${{ matrix.build-mono }}
-        run: |
-          echo "MONO_SCONSFLAGS=module_mono_enabled=yes mono_glue=yes copy_mono_root=yes mono_bcl=$HOME/mono-bcls/desktop-bcl/net_4_x" >> $GITHUB_ENV
+  #     - name: Set Mono scons flags
+  #       if: ${{ matrix.build-mono }}
+  #       run: |
+  #         echo "MONO_SCONSFLAGS=module_mono_enabled=yes mono_glue=yes copy_mono_root=yes mono_bcl=$HOME/mono-bcls/desktop-bcl/net_4_x" >> $GITHUB_ENV
 
-      - name: Clear bin
-        run: |
-          rm -rf bin
+  #     - name: Clear bin
+  #       run: |
+  #         rm -rf bin
 
-      # Editor
-      - name: Compilation
-        uses: ./.github/actions/redot-build
-        with:
-          buildroot: "${{ github.workspace }}/x86_64-godot-linux-gnu_sdk-buildroot/bin"
-          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-linux-x86_64-release' || '' }}
-          platform: linuxbsd
-          target: editor
-          tools: true
+  #     # Editor
+  #     - name: Compilation
+  #       uses: ./.github/actions/redot-build
+  #       with:
+  #         buildroot: "${{ github.workspace }}/x86_64-godot-linux-gnu_sdk-buildroot/bin"
+  #         sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-linux-x86_64-release' || '' }}
+  #         platform: linuxbsd
+  #         target: editor
+  #         tools: true
 
-      - name: Generate C# glue
-        if: ${{ matrix.build-mono }}
-        run: |
-          ${{ matrix.bin }} --headless --generate-mono-glue ./redot-engine/modules/mono/glue
+  #     - name: Generate C# glue
+  #       if: ${{ matrix.build-mono }}
+  #       run: |
+  #         ${{ matrix.bin }} --headless --generate-mono-glue ./redot-engine/modules/mono/glue
 
-      - name: Build .NET solutions
-        if: ${{ matrix.build-mono }}
-        run: |
-          ./redot-engine/modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./redot-engine/bin --godot-platform=linuxbsd
+  #     - name: Build .NET solutions
+  #       if: ${{ matrix.build-mono }}
+  #       run: |
+  #         ./redot-engine/modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./redot-engine/bin --godot-platform=linuxbsd
 
-      - name: Prep Executables
-        shell: bash
-        run: |
-          strip redot-engine/bin/redot.*
-          chmod +x redot-engine/bin/redot.*
+  #     - name: Prep Executables
+  #       shell: bash
+  #       run: |
+  #         strip redot-engine/bin/redot.*
+  #         chmod +x redot-engine/bin/redot.*
 
-      - name: Upload Editor
-        uses: ./.github/actions/upload-artifact
-        with:
-          name: ${{ matrix.cache-name }}-editor-64
-          path: redot-engine/bin
+  #     - name: Upload Editor
+  #       uses: ./.github/actions/upload-artifact
+  #       with:
+  #         name: ${{ matrix.cache-name }}-editor-64
+  #         path: redot-engine/bin
 
-      - name: Clear bin
-        run: |
-          rm -rf bin
+  #     - name: Clear bin
+  #       run: |
+  #         rm -rf bin
 
-      # Templates
-      - name: Compilation
-        uses: ./.github/actions/redot-build
-        with:
-          buildroot: "${{ github.workspace }}/x86_64-godot-linux-gnu_sdk-buildroot/bin"
-          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-linux-x86_64-release' || '' }}
-          platform: linuxbsd
-          target: template_release
-          tools: false
+  #     # Templates
+  #     - name: Compilation
+  #       uses: ./.github/actions/redot-build
+  #       with:
+  #         buildroot: "${{ github.workspace }}/x86_64-godot-linux-gnu_sdk-buildroot/bin"
+  #         sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-linux-x86_64-release' || '' }}
+  #         platform: linuxbsd
+  #         target: template_release
+  #         tools: false
 
-      - name: Compilation
-        uses: ./.github/actions/redot-build
-        with:
-          buildroot: "${{ github.workspace }}/x86_64-godot-linux-gnu_sdk-buildroot/bin"
-          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-linux-x86_64-release' || '' }} debug_symbols=no
-          platform: linuxbsd
-          target: template_release
-          tools: false
+  #     - name: Compilation
+  #       uses: ./.github/actions/redot-build
+  #       with:
+  #         buildroot: "${{ github.workspace }}/x86_64-godot-linux-gnu_sdk-buildroot/bin"
+  #         sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-linux-x86_64-release' || '' }} debug_symbols=no
+  #         platform: linuxbsd
+  #         target: template_release
+  #         tools: false
 
-      - name: Upload Templates
-        uses: ./.github/actions/upload-artifact
-        with:
-          name: ${{ matrix.cache-name }}-templates-64
-          path: redot-engine/bin
+  #     - name: Upload Templates
+  #       uses: ./.github/actions/upload-artifact
+  #       with:
+  #         name: ${{ matrix.cache-name }}-templates-64
+  #         path: redot-engine/bin
 
-      - name: Clear bin
-        run: |
-          rm -rf bin
+  #     - name: Clear bin
+  #       run: |
+  #         rm -rf bin
   windows:
     runs-on: "ubuntu-latest"
     name: 🏁 Windows-64 ${{ matrix.name }}
@@ -199,11 +199,11 @@ jobs:
       fail-fast: false
       matrix:
         include:
-#           - name: Editor & Templates
-#             cache-name: windows-64
-#             bin: ./redot-engine/bin/redot.windows.editor.x86_64.exe
-#             artifact-name: windows
-#             build-mono: false
+          # - name: Editor & Templates
+          #   cache-name: windows-64
+          #   bin: ./redot-engine/bin/redot.windows.editor.x86_64.exe
+          #   artifact-name: windows
+          #   build-mono: false
 
           - name: Editor & Templates w/ Mono
             cache-name: windows-64-mono
@@ -276,7 +276,7 @@ jobs:
         uses: ./.github/actions/redot-build
         with:
           sconsflags: mono_static=yes module_mono_enabled=yes mono_glue=no
-          platform: linuxbsd
+          platform: windows
           tools: true
 
       # Generate mono glue
@@ -308,7 +308,7 @@ jobs:
         with:
           sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-windows-x86_64-release' || '' }}
           platform: windows
-          target: release_debug
+          target: editor
           tools: true
 
       - name: Generate C# glue
@@ -336,7 +336,7 @@ jobs:
         with:
           sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-windows-x86_64-release' || '' }}
           platform: windows
-          target: release_debug
+          target: template_release
           tools: false
 
       - name: Compilation (tools=false, bits=64, target=release)
@@ -344,7 +344,7 @@ jobs:
         with:
           sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-windows-x86_64-release' || '' }} debug_symbols=no
           platform: windows
-          target: release
+          target: template_release
           tools: false
 
       - name: Upload Templates
